version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - static:/webserver/static
      - media:/webserver/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - web
  db:
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - settings.env
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - static:/webserver/static/
      - media:/webserver/media/
      - tours_migrations:/webserver/tours/migrations
    ports:
      - 8000:8000
    env_file:
      - settings.env
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- ./start-server.sh


volumes:
  static:
  media:
  pg_data:
  tours_migrations:

